// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhOjfqw6pMwW3dHBoT_o8CptnxTcQd0_Y',
    appId: '1:982037833299:web:ce83a467b5673699e788a6',
    messagingSenderId: '982037833299',
    projectId: 'electromart-20b9f',
    authDomain: 'electromart-20b9f.firebaseapp.com',
    storageBucket: 'electromart-20b9f.appspot.com',
    measurementId: 'G-4NCE7W675F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf2gZu5GxMW29x4f019CXhjv3SAOAJAKg',
    appId: '1:982037833299:android:dcd4203f398d5e9ee788a6',
    messagingSenderId: '982037833299',
    projectId: 'electromart-20b9f',
    storageBucket: 'electromart-20b9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTox_fCY84mlzIhOiHPE2rcQobd8zVmHQ',
    appId: '1:982037833299:ios:b5a38f71f3634d05e788a6',
    messagingSenderId: '982037833299',
    projectId: 'electromart-20b9f',
    storageBucket: 'electromart-20b9f.appspot.com',
    iosBundleId: 'com.example.electromart',
  );
}
